# Generated by Django 4.2.7 on 2025-12-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dept_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.dept'),
        ),
    ]
