# Generated by Django 4.2.7 on 2025-12-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_emp_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='dept',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='test.png', upload_to='image'),
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
