# Generated by Django 4.2.7 on 2026-01-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_dept_comany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='comany',
            new_name='company',
        ),
    ]
