# Generated by Django 4.2.7 on 2026-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_comany_dept_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
